### ISSUE TITLE
Thunderbird Beta install fails.

### ISSUE THREAD

**Issue by ringods** [Homebrew/homebrew-cask-versions#18489]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

I want to install Thunderbird Beta but it fails.

When checking the downloaded DMG file, the app inside of it is not named `Thunderbird.app`, but `Thunderbird Beta.app`

### Command that failed

brew install --cask thunderbird-beta

### Output of command with `--verbose --debug`

```shell
$ brew install --cask thunderbird-beta --verbose --debug
==> Cask::Installer#install
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading thunderbird
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://download.mozilla.org/?product=thunderbird-beta-latest-SSL&os=osx&lang=en-GB
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.21-42-gdbcb475\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.1.1\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://download.mozilla.org/\?product=thunderbird-beta-latest-SSL\&os=osx\&lang=en-GB
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.21-42-gdbcb475\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.1.1\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://download.mozilla.org/\?product=thunderbird-beta-latest-SSL\&os=osx\&lang=en-GB
Already downloaded: /Users/ringods/Library/Caches/Homebrew/downloads/f5852c3b6542e08398b8ee6a4ebc0748b4f6fbcad0b6b38e11403309dac2b7a3--Thunderbird 121.0b1.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target x86_64-apple-macosx14 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/ringods/Library/Caches/Homebrew/downloads/f5852c3b6542e08398b8ee6a4ebc0748b4f6fbcad0b6b38e11403309dac2b7a3--Thunderbird 121.0b1.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/ringods/Library/Caches/Homebrew/downloads/f5852c3b6542e08398b8ee6a4ebc0748b4f6fbcad0b6b38e11403309dac2b7a3--Thunderbird\ 121.0b1.dmg
==> /Users/ringods/Library/Caches/Homebrew/downloads/f5852c3b6542e08398b8ee6a4ebc0748b4f6fbcad0b6b38e11403309dac2b7a3--Thunderbird 121.0b1.dmg is quarantined
Warning: No checksum defined for cask 'thunderbird-beta', skipping verification.
/usr/bin/env tar --list --file /Users/ringods/Library/Caches/Homebrew/downloads/f5852c3b6542e08398b8ee6a4ebc0748b4f6fbcad0b6b38e11403309dac2b7a3--Thunderbird\ 121.0b1.dmg
/usr/bin/env hdiutil imageinfo -format /Users/ringods/Library/Caches/Homebrew/downloads/f5852c3b6542e08398b8ee6a4ebc0748b4f6fbcad0b6b38e11403309dac2b7a3--Thunderbird\ 121.0b1.dmg
==> Installing Cask thunderbird-beta
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/ringods/Library/Caches/Homebrew/downloads/f5852c3b6542e08398b8ee6a4ebc0748b4f6fbcad0b6b38e11403309dac2b7a3--Thunderbird 121.0b1.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20231125-2326-101hban /Users/ringods/Library/Caches/Homebrew/downloads/f5852c3b6542e08398b8ee6a4ebc0748b4f6fbcad0b6b38e11403309dac2b7a3--Thunderbird\ 121.0b1.dmg
/usr/bin/env find . -print0
/usr/bin/env mkbom -s -i /private/tmp/20231125-2326-9cn01h.list -- /private/tmp/20231125-2326-92n9sc.bom
/usr/bin/env ditto --bom /private/tmp/20231125-2326-92n9sc.bom -- /private/tmp/d20231125-2326-101hban/dmg.oPOhYB /private/tmp/d20231125-2326-kpwyc1
/usr/bin/env diskutil info -plist /private/tmp/d20231125-2326-101hban/dmg.oPOhYB
/usr/bin/env diskutil eject /private/tmp/d20231125-2326-101hban/dmg.oPOhYB
/usr/bin/env cp -pR /private/tmp/d20231125-2326-kpwyc1/Thunderbird\ Beta.app/. /usr/local/Caskroom/thunderbird-beta/latest/Thunderbird\ Beta.app
==> Verifying Gatekeeper status of /Users/ringods/Library/Caches/Homebrew/downloads/f5852c3b6542e08398b8ee6a4ebc0748b4f6fbcad0b6b38e11403309dac2b7a3--Thunderbird 121.0b1.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/ringods/Library/Caches/Homebrew/downloads/f5852c3b6542e08398b8ee6a4ebc0748b4f6fbcad0b6b38e11403309dac2b7a3--Thunderbird\ 121.0b1.dmg
==> /Users/ringods/Library/Caches/Homebrew/downloads/f5852c3b6542e08398b8ee6a4ebc0748b4f6fbcad0b6b38e11403309dac2b7a3--Thunderbird 121.0b1.dmg is quarantined
==> Propagating quarantine from /Users/ringods/Library/Caches/Homebrew/downloads/f5852c3b6542e08398b8ee6a4ebc0748b4f6fbcad0b6b38e11403309dac2b7a3--Thunderbird 121.0b1.dmg to /usr/local/Caskroom/thunderbird-beta/latest
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/ringods/Library/Caches/Homebrew/downloads/f5852c3b6542e08398b8ee6a4ebc0748b4f6fbcad0b6b38e11403309dac2b7a3--Thunderbird\ 121.0b1.dmg
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0381\;6561b318\;\;F08174C6-34CF-4FBA-96E6-74D781231959
==> Creating metadata directory: /usr/local/Caskroom/thunderbird-beta/.metadata/latest/20231125085809.064
==> Creating metadata subdirectory: /usr/local/Caskroom/thunderbird-beta/.metadata/latest/20231125085809.064/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::App
==> Purging files for version latest of Cask thunderbird-beta
Error: It seems the App source '/usr/local/Caskroom/thunderbird-beta/latest/Thunderbird.app' is not there.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:39:in `move'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:19:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:229:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:222:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:110:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:244:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```
```


### Output of `brew doctor` and `brew config`

```shell
`brew doctor` output:


Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  dep
  dockutil
  octant
  openssl@1.1

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-cask-drivers
Untap them with `brew untap`.

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  pygments
  dockutil
  yamllint

Warning: You have an unnecessary local Core tap!
This can cause problems installing up-to-date formulae.
Please remove it by running:
 brew untap homebrew/core
```

`brew config` output:

```
HOMEBREW_VERSION: 4.1.21-42-gdbcb475
ORIGIN: https://github.com/Homebrew/brew
HEAD: dbcb475b3b50aa91e6e375c9f4c2fe5b951b4648
Last commit: 18 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7213ad946b28987c9dfcb6371a6f41422f97f52e
Core tap last commit: 2 hours ago
Core tap branch: master
Core tap JSON: 25 Nov 08:51 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.43.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.1.1-x86_64
CLT: 15.0.0.0.1.1694021235
Xcode: 15.0.1
```
```


### Output of `brew tap`

```shell
buo/cask-upgrade
dagger/tap
derailed/k9s
golangci/tap
goreleaser/tap
hashicorp/tap
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
hpedrorodrigues/tools
isen-ng/dotnet-sdk-versions
pulumi/tap
siderolabs/talos
updatecli/updatecli
```
```

**Comment by bevanjkay** [comment]
@ringods Thank you for reporting this issue, I have opened a PR to fix.
